home_leftsidebar(user) ::= <<

     <div class="col-xs-2">
            <a href="#" class="thumbnail">
                <img src="/files/images/logo.jpg" alt="125x125">
            </a>

			<div class="list-group">
				<a href="/compose" class="list-group-item active">
					<span class="glyphicon glyphicon-pencil"></span> Compose
				</a>
				<a href="#" class="list-group-item">
					<span class="glyphicon glyphicon-envelope"></span> Inbox <span class="badge">145</span>
				</a>
				<a href="#" class="list-group-item">
					<span class="glyphicon glyphicon-share"></span> Sent <span class="badge">50</span>
				</a>
				<a href="#" class="list-group-item">
					<span class="glyphicon glyphicon-trash"></span> Trash <span class="badge">8</span>
				</a>
			</div>
	</div>

>>