login() ::= <<

   <br>

   <div class="container">
     <div class="row">
   	<div class="col-xs-4">
   	</div>

   	<div class="col-xs-4">
   	  <a href="#" class="thumbnail">
           <img src="/files/images/logo.jpg" alt="125x125">
         </a>

   	  <form class="form-signin" role="form" method=post action=/loginprocessor>
   		<h3 class="form-signin-heading">Please sign in</h3>
   		<input type="text" name= "username" class="form-control" placeholder="username" required autofocus>
   		<input type="password" name="password" class="form-control" placeholder="Password" required>
   		<div class="checkbox">
   		  <label>
   			<input type="checkbox" value="remember-me"> Remember me
   		  </label>
   		</div>
   		<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
   	  </form>

   	  <br>

   	  <p> Don't have an account? &nbsp; <a href="/register"> Create </a>
   	  </p>
   	</div>

       <div class="col-xs-4">
   	</div>
     </div>
   </div> <!-- /container -->





>>