page(title, body) ::= <<
<html>

<head>
       <meta charset="utf-8">
       <title>$title$</title>
       <meta name="viewport" content="width=device-width, initial-scale=1.0">
   	<!-- include the following Bootstrap files-->
       <link rel="stylesheet" type="text/css" href="/files/css/bootstrap.min.css">
       <link rel="stylesheet" type="text/css" href="/files/css/bootstrap-theme.min.css">
   	   <script src="http://code.jquery.com/jquery.min.js"></script>
       <script src="/files/js/bootstrap.min.js"></script>
</head>

<body>
    $body$
</body>

</html>
>>
