tabledisplay(user) ::= <<

<div class="panel panel-primary">
				<!--
				<div class="panel-heading">
					Panel heading without title
				</div>
				-->

				<div class="panel-body">
					<table class="table table-hover">
						<thead>
							<tr>
								<th>Datetime</th>
								<th>Sender</th>
								<th>Subject</th>
								<th>Message</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>2014-11-2 10:30am</td>
								<td>Su Xue</td>
								<td>A Test</td>
								<td>"Hello world..."</td>
							</tr>
							<tr>
								<td>2014-10-30 9:30am</td>
								<td>Chao Chen</td>
								<td>My Birthday</td>
								<td>"Wish me happy birthday..."</td>
							</tr>
							<tr>
								<td>2014-10-24 6:09pm</td>
								<td>Ye Liyang</td>
								<td>My Birthday</td>
								<td>"I want to stay in lab..."</td>
							</tr>
						</tbody>
					</table>
				<div>
				<!--
				<div class="panel-footer">
					Panel footer
				</div>
				-->
			</div>
>>