welcome(name) ::= <<
<br><br>

<div class="container">
	<div class="row">
		<div class="col-xs-4">
		</div>
		<div class="col-xs-4">
			<div class="text-center">
				<h1>Welcome, $name$! </h1>
				<h1><small> SMail - A Webmail Service</small></h1>
				<p><a href="#" class="thumbnail">
					<img src="/files/images/logo.jpg" alt="125x125">
				</a></p>
				<a href="/inbox" type="button" class="btn btn-primary btn-lg">
					Get Started
				</a>
			</div>
		</div>
		<div class="col-xs-4">
		</div>
	</div>
</div>
>>
